"""initial migration

Revision ID: c5373be12952
Revises: 
Create Date: 2026-09-24 09:05:05.308705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5373be12952'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moderation_case',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('moderator_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('WARN', 'TIMEOUT', 'BAN', 'KICK', 'REMOVE_TIMEOUT', 'UNBAN', 'UNWARN', name='moderation_cases'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('removed_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moderation_case_guild_id'), 'moderation_case', ['guild_id'], unique=False)
    op.create_index(op.f('ix_moderation_case_moderator_id'), 'moderation_case', ['moderator_id'], unique=False)
    op.create_index(op.f('ix_moderation_case_user_id'), 'moderation_case', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_moderation_case_user_id'), table_name='moderation_case')
    op.drop_index(op.f('ix_moderation_case_moderator_id'), table_name='moderation_case')
    op.drop_index(op.f('ix_moderation_case_guild_id'), table_name='moderation_case')
    op.drop_table('moderation_case')
    # ### end Alembic commands ###
